version: '1.0'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./cpsolver:/app/cpsolver
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=info
      - SOLVER_PATH=/app/cpsolver
    restart: unless-stopped
    
  # db:
  #   image: postgres:15-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=unitime
  #     - POSTGRES_PASSWORD=unitimepassword
  #     - POSTGRES_DB=unitime
  #   ports:
  #     - "5432:5432"
      
# volumes:
#   postgres_data:
